// svelte/src/routes/timer/+page.svelte
<script lang="ts">
	let elapsed = $state(1);
	let duration = $state(50);

	const percentage = $derived((elapsed * 100) / duration);

	$effect(() => {
		const interval = setInterval(() => {
			elapsed += 0.1;
		}, 100);

		return () => clearInterval(interval);
	});
</script>

<div class="grid grid-cols-1 gap-6">
	<label class="label"
		>Elapsed: <progress class="progress ml-5" value={percentage} max={100}></progress></label
	>

	<span class="text-white">{elapsed.toFixed(1)} s</span>

	<label class="label">
		Duration ({duration}s):
		<input
			type="range"
			class="range range-xs ml-5"
			min={0.1}
			max={100}
			step={0.1}
			bind:value={duration}
		/>
	</label>

	<button
		class="btn"
		onclick={() => {
			elapsed = 0;
		}}>Reset</button
	>
</div>

// react/src/components/Timer.tsx
import {
  Text,
  Fieldset,
  Group,
  Progress,
  Slider,
  Button,
  Center,
} from "@mantine/core"
import {
  type FC,
  useEffect,
  useMemo,
  useState,
  forwardRef,
  useImperativeHandle,
  useRef,
  useCallback,
} from "react"

const TimerDisplay = forwardRef<() => void, { duration: number }>(
  ({ duration }, ref) => {
    const [elapsed, setElapsed] = useState(0)
    const percentage = useMemo(
      () => (elapsed * 100) / duration,
      [elapsed, duration],
    )

    useEffect(() => {
      const interval = setInterval(() => {
        setElapsed((val) => val + 0.1)
      }, 100)

      return () => clearInterval(interval)
    }, [])

    const resetTimer = useCallback(() => {
      setElapsed(0)
    }, [])

    useImperativeHandle(ref, () => resetTimer)

    return (
      <>
        <Group variant="label" grow wrap="nowrap">
          Elapsed:
          <Progress
            my={16}
            value={percentage}
            size="lg"
            miw={400}
            transitionDuration={200}
          />
        </Group>

        <Text>{elapsed.toFixed(2)} s</Text>
      </>
    )
  },
)

const Timer = () => {
  const [duration, setDuration] = useState(50)
  const timerRef = useRef<() => void>(() => {})

  return (
    <Fieldset miw="30%" h="100%">
      <TimerDisplay ref={timerRef} duration={duration} />

      <Text mt="1rem">Duration:</Text>
      <Slider
        min={0.1}
        max={100}
        step={0.1}
        value={duration}
        onChange={(e) => {
          setDuration(e)
        }}
      />

      <Center mt="1rem">
        <Button onClick={() => timerRef.current()}>Reset</Button>
      </Center>
    </Fieldset>
  )
}

export default Timer
